from decimal import Decimal
from sqlalchemy import Column, Integer, String, BigInteger, Numeric
from src.models.base import Base


class TeamForm(Base):
    __tablename__ = "mart_team_form"
    
    team_id = Column(Integer, primary_key=True)
    team_name = Column(String)
    season_id = Column(Integer, primary_key=True)
    season_name = Column(String)
    season_year = Column(String)
    last_5_results = Column(String)
    points_last_5 = Column(BigInteger)
    wins_last_5 = Column(BigInteger)
    draws_last_5 = Column(BigInteger)
    losses_last_5 = Column(BigInteger)
    goals_for_last_5 = Column(BigInteger)
    goals_against_last_5 = Column(BigInteger)
    last_10_results = Column(String)
    points_last_10 = Column(BigInteger)
    wins_last_10 = Column(BigInteger)
    draws_last_10 = Column(BigInteger)
    losses_last_10 = Column(BigInteger)
    goals_for_last_10 = Column(BigInteger)
    goals_against_last_10 = Column(BigInteger)
    last_15_results = Column(String)
    points_last_15 = Column(BigInteger)
    wins_last_15 = Column(BigInteger)
    draws_last_15 = Column(BigInteger)
    losses_last_15 = Column(BigInteger)
    goals_for_last_15 = Column(BigInteger)
    goals_against_last_15 = Column(BigInteger)
    last_20_results = Column(String)
    points_last_20 = Column(BigInteger)
    wins_last_20 = Column(BigInteger)
    draws_last_20 = Column(BigInteger)
    losses_last_20 = Column(BigInteger)
    goals_for_last_20 = Column(BigInteger)
    goals_against_last_20 = Column(BigInteger)
    halftime_leading_count = Column(BigInteger)
    halftime_leading_wins = Column(BigInteger)
    halftime_leading_draws = Column(BigInteger)
    halftime_leading_losses = Column(BigInteger)
    halftime_leading_win_pct = Column(Numeric)
    conceded_first_count = Column(BigInteger)
    points_after_conceding_first = Column(BigInteger)
    points_pct_after_conceding_first = Column(Numeric)
    last_5_results_home = Column(String)
    points_last_5_home = Column(BigInteger)
    last_5_results_away = Column(String)
    points_last_5_away = Column(BigInteger)